//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sccmclictr.automation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sccmclictr.automation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a=New-Object -comObject &apos;CPAPPLET.CPAppletMgr&apos;;($a.GetClientProperties() | Where-Object { $_.Name -eq &apos;ADSiteName&apos; }).Value.
        /// </summary>
        internal static string ADSiteName {
            get {
                return ResourceManager.GetString("ADSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a=Get-Wmiobject -class SMS_Client -namespace &apos;ROOT\CCM&apos;;$a.AllowLocalAdminOverride.
        /// </summary>
        internal static string AllowLocalAdminOverride {
            get {
                return ResourceManager.GetString("AllowLocalAdminOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a = (Get-Wmiobject -class SMS_Client -namespace &apos;ROOT\\CCM&apos;);$a.AllowLocalAdminOverride = ${0};$a.Put();.
        /// </summary>
        internal static string AllowLocalAdminOverride_Set {
            get {
                return ResourceManager.GetString("AllowLocalAdminOverride_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Get-Wmiobject -class CCM_ClientAgentSettings -namespace &apos;ROOT\CCM\ClientSDK&apos;).BrandingTitle.
        /// </summary>
        internal static string BrandingTitle {
            get {
                return ResourceManager.GetString("BrandingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get-WmiObject -Class CCM_Application -Namespace &quot;root\ccm\clientsdk&quot;.
        /// </summary>
        internal static string CCM_Application {
            get {
                return ResourceManager.GetString("CCM_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a=New-Object -comObject &apos;CPAPPLET.CPAppletMgr&apos;;($a.GetClientProperties() | Where-Object { $_.Name -eq &apos;CertKeyType&apos; }).Value.
        /// </summary>
        internal static string CertKeyType {
            get {
                return ResourceManager.GetString("CertKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a=[wmiclass]&quot;root\ccm\clientsdk:CCM_SoftwareCatalogUtilities&quot;;$a.GetDeviceID().ClientID.
        /// </summary>
        internal static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Get-Wmiobject -class CCM_Client -namespace &apos;ROOT\CCM&apos;).ClientIDChangeDate.
        /// </summary>
        internal static string ClientIdChangeDate {
            get {
                return ResourceManager.GetString("ClientIdChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Get-Wmiobject -class SMS_Client -namespace &apos;ROOT\CCM&apos;).ClientType.
        /// </summary>
        internal static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a=[wmiclass]&quot;root\ccm\clientsdk:CCM_SoftwareCatalogUtilities&quot;;$a.GetClientVersion().ClientVersion.
        /// </summary>
        internal static string ClientVersion {
            get {
                return ResourceManager.GetString("ClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a=New-Object -comObject &apos;CPAPPLET.CPAppletMgr&apos;;($a.GetClientProperties() | Where-Object { $_.Name -eq &apos;CommunicationMode&apos; }).Value.
        /// </summary>
        internal static string CommunicationMode {
            get {
                return ResourceManager.GetString("CommunicationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Get-Wmiobject -class SMS_Client -namespace &apos;ROOT\CCM&apos;).EnableAutoAssignment.
        /// </summary>
        internal static string EnableAutoAssignment {
            get {
                return ResourceManager.GetString("EnableAutoAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a = (Get-Wmiobject -class SMS_Client -namespace &apos;ROOT\\CCM&apos;);$a.EnableAutoAssignment = ${0};$a.Put().
        /// </summary>
        internal static string EnableAutoAssignment_Set {
            get {
                return ResourceManager.GetString("EnableAutoAssignment_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a=[wmiclass]&quot;root\ccm\clientsdk:CCM_ClientInternalUtilities&quot;;$a.AreMultiUsersLoggedOn().MultiUsersLoggedOn.
        /// </summary>
        internal static string MultiUsersLoggedOn {
            get {
                return ResourceManager.GetString("MultiUsersLoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Get-Wmiobject -class CCM_Client -namespace &apos;ROOT\CCM&apos;).PreviousClientId.
        /// </summary>
        internal static string PreviousClientId {
            get {
                return ResourceManager.GetString("PreviousClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $a=[wmiclass]&quot;root\ccm\clientsdk:CCM_ClientUtilities&quot;;$a.DetermineIfRebootPending().
        /// </summary>
        internal static string RebootPending {
            get {
                return ResourceManager.GetString("RebootPending", resourceCulture);
            }
        }
    }
}
